#!/usr/bin/env python3
"""auto-commit-run-report.py — PostToolUse hook (Bash matcher).

When Claude Code (or any subagent) runs `scripts/alpha_factory/
generate_run_report.py`, this hook scans for newly-created
`reports/run-reports/run-N.md` and `run-N/` artifacts and commits them.

Why a hook (rather than embedding `git commit` in the Python script):
- The script is also imported and invoked by skill / improve-cycle
  orchestrators; embedding VCS in the script tangles concerns.
- PostToolUse fires regardless of how Bash was invoked (skill, agent,
  manual user command).
- Failure to commit MUST NOT break the upstream tool result, so this
  script always exits 0 and only logs to stderr.

Input contract (Claude Code 2.x):
- JSON object on stdin: { tool_name, tool_input: { command, ... }, ... }.
- We only react when tool_name == "Bash" and command mentions
  `generate_run_report.py`.

Side effects:
- Adds untracked `reports/run-reports/run-*.md` and `run-*/` whose mtime
  is within the last 60 seconds (filters out unrelated stale untracked).
- Single commit per invocation, none if nothing fresh.
- Operates only inside `$CLAUDE_PROJECT_DIR` (or pwd).
"""
from __future__ import annotations

import json
import os
import re
import subprocess
import sys
import time
from pathlib import Path

LOG_TAG = "auto-commit-run-report"
RUN_NAME_RE = re.compile(r"^reports/run-reports/run-([0-9]+)(/|\.md$)")
FRESH_WINDOW_SECONDS = 60


def _log(msg: str) -> None:
    print(f"[{LOG_TAG}] {msg}", file=sys.stderr)


def _read_payload() -> dict:
    try:
        return json.loads(sys.stdin.read())
    except Exception:
        return {}


def _git(*args: str, cwd: Path) -> tuple[int, str, str]:
    proc = subprocess.run(
        ["git", *args],
        cwd=cwd,
        capture_output=True,
        text=True,
    )
    return proc.returncode, proc.stdout, proc.stderr


def _is_git_repo(cwd: Path) -> bool:
    rc, _, _ = _git("rev-parse", "--is-inside-work-tree", cwd=cwd)
    return rc == 0


def _candidate_paths(cwd: Path) -> list[str]:
    """Return relative paths under reports/run-reports/run-N{,.md} that
    are either untracked or modified, filtered to fresh mtime."""
    rc, untracked_out, _ = _git(
        "ls-files",
        "--others",
        "--exclude-standard",
        "reports/run-reports",
        cwd=cwd,
    )
    untracked = untracked_out.splitlines() if rc == 0 else []

    rc, modified_out, _ = _git(
        "diff", "--name-only", "--", "reports/run-reports", cwd=cwd
    )
    modified = modified_out.splitlines() if rc == 0 else []

    seen: set[str] = set()
    matches: list[str] = []
    for path in (*untracked, *modified):
        if not RUN_NAME_RE.match(path):
            continue
        if path in seen:
            continue
        seen.add(path)
        matches.append(path)

    now = time.time()
    fresh: list[str] = []
    for rel in matches:
        full = cwd / rel
        if not full.exists():
            continue
        try:
            mtime = full.stat().st_mtime
        except OSError:
            continue
        if (now - mtime) <= FRESH_WINDOW_SECONDS:
            fresh.append(rel)
    return fresh


def _run_numbers(paths: list[str]) -> list[str]:
    nums: set[int] = set()
    for p in paths:
        m = RUN_NAME_RE.match(p)
        if m:
            nums.add(int(m.group(1)))
    return [str(n) for n in sorted(nums)]


def main() -> int:
    payload = _read_payload()
    if payload.get("tool_name") != "Bash":
        return 0

    command = (payload.get("tool_input") or {}).get("command", "") or ""
    if "generate_run_report.py" not in command:
        return 0

    cwd = Path(os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd())
    if not _is_git_repo(cwd):
        return 0

    if not (cwd / "reports" / "run-reports").is_dir():
        return 0

    paths = _candidate_paths(cwd)
    if not paths:
        return 0

    runs = _run_numbers(paths)
    if not runs:
        return 0

    rc, _, err = _git("add", "--", *paths, cwd=cwd)
    if rc != 0:
        _log(f"git add failed: {err.strip()}")
        return 0

    rc, _, _ = _git(
        "diff", "--cached", "--quiet", "--", *paths, cwd=cwd
    )
    if rc == 0:
        # Nothing actually staged (e.g. paths already tracked unchanged).
        return 0

    runs_csv = ",".join(runs)
    msg_lines = [
        f"docs(reports): auto-commit run-{runs_csv} after generate_run_report",
        "",
        "Generated by .claude/hooks/auto-commit-run-report.py after a Bash",
        "invocation of scripts/alpha_factory/generate_run_report.py.",
        "",
        f"Run numbers: {runs_csv}",
        "",
        "Co-Authored-By: Claude Opus 4.7 (1M context) <noreply@anthropic.com>",
    ]
    rc, _, err = _git(
        "commit", "-m", "\n".join(msg_lines), cwd=cwd
    )
    if rc != 0:
        _log(f"git commit failed: {err.strip()}")
        return 0

    _log(f"committed run-{runs_csv} ({len(paths)} paths)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
